### ISSUE TITLE
`svg` macro fails in cross-rs build

### ISSUE THREAD

**Issue by rgwood** [wrapperup/iconify-rs#38]
Hello and thank you for writing this very useful crate!

I use [`cross-rs`](https://github.com/cross-rs/cross) for cross-compilation of my Rust projects, and I've noticed that `iconify::svg!()` fails when building my projects in `cross-rs`.

For example, if I try to build for `aarch64-unknown-linux-musl` by running `cross build --target aarch64-unknown-linux-musl` it fails with:
```
error: proc macro panicked
   --> src/main.rs:462:32
    |
462 |                 icon_svg: Some(iconify::svg!("mdi:image").into()),
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
 ```
    
 `cross-rs` works by compiling inside a Docker container, so I'm guessing it's something to do with not being able to write to the local filesystem.

**Comment by wrapperup** [comment]
Hi, thanks for using this crate! The issue is probably that it's trying to write icons to a cache folder that it has no access to. There's a few fixes you can try:

1. Use offline mode, there's instructions in the README on how to use it. For Docker deployment, this is probably your best bet.
2. Change the cache directory by setting the `ICONIFY_CACHE_DIR` env var to a directory with permissions you control.
3. Disable the `cache` feature. It will send a request on every build and invocation of the macro, so I would probably avoid this.

Let me know if this helps! I'd like to make this process better if I can.

**Comment by rgwood** [comment]
I’ll take a closer look at this when I have time, thanks for the quick response.

It would be nice to make this “just work” without manual configuration under cross-rs if possible, I’ll submit a PR if I figure out a good way to do that.

**Comment by rgwood** [comment]
OK, had a bit of time to look into this. `iconify-rs` is using [`directories`](https://crates.io/crates/directories), which returns a `cache_dir` value of `/.cache` when run in the Docker images that `cross-rs` uses. Unfortunately `/.cache` doesn't exist or isn't writable.

To work around this in my own project, I think I'm going to use a build script to tell `iconify-rs` to use the `/tmp` directory instead which works fine:
```rust
fn main() {
    if is_docker::is_docker() {
        println!("cargo:rustc-env=ICONIFY_CACHE_DIR=/tmp/iconify/");
    }
}
```

It would be nice if this were unnecessary though, I kinda think it would make sense for `iconify-rs` to default to `/tmp` on *nix. Would you welcome a PR along those lines?

**Comment by wrapperup** [comment]
> It would be nice if this were unnecessary though, I kinda think it would make sense for `iconify-rs` to default to `/tmp` on *nix. Would you welcome a PR along those lines?

Yep, that makes sense. I don't have any strong opinions on where the cache directory should be by default 👍. Probably better to default to something more sensible.
